version: '3'

services:
  api:
    build:
      context: ../
      dockerfile: ./docker/local.api.Dockerfile
    volumes:
      - ../app/server/:/home/nodejs/app
    restart: unless-stopped
    networks:
      - crawling
    ports:
      - "3001:3001"

  redis:
    image: bitnami/redis:6.2
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - crawling
    logging:
      driver: "none"

volumes:
  mathan_loans_db_data:
  pgadmin:


networks:
  crawling:
    external: false
